graasp/graasp-builder

.github/workflows/deployProd.yml, src/serviceWorker.js
=> build: add deploy to prod workflow

cypress/fixtures/members.js, cypress/integration/item/favorite/favoriteItem.spec.js, src/components/App.js, src/components/layout/Navigation.js, src/components/main/FavoriteItems.js, src/components/main/ItemMenu.js, src/components/main/MainMenu.js, src/config/paths.js, src/config/selectors.js, src/langs/en.json, src/langs/fr.json, src/utils/item.js, src/utils/member.js
=> Add favorites items

.github/workflows/deployProd.yml, yarn.lock
=> refactor: update yarn.lock, deploy prod only on tag

cypress/integration/item/copy/listCopyItem.spec.js, cypress/integration/item/delete/listDeleteItem.spec.js, cypress/integration/item/delete/listDeleteItems.spec.js, cypress/integration/item/move/listMoveItem.spec.js, cypress/integration/item/order/reorderItems.spec.js, cypress/support/constants.js, src/components/main/CustomCardHeader.js, src/components/main/ItemMenu.js, src/components/main/ItemsTable.js, yarn.lock
Update `graasp-query-client` to latest.
Fixes the following in `graasp-compose`:
- https://github.com/graasp/graasp-compose/issues/143
- https://github.com/graasp/graasp-query-client/issues/20
=> chore: update graasp-query-client to 525f297

src/enums/permissionLevels.js
=> refactor: permission_levels order

cypress/integration/item/favorite/favoriteItem.spec.js, src/components/common/FavoriteButton.js, src/components/main/CustomCardHeader.js, src/components/main/Item.js, src/components/main/ItemMenu.js, src/components/main/ItemsTable.js, src/config/selectors.js
=> Show favorite item button in table/grid view

package.json, src/index.js, yarn.lock
=> refactor: import graasp ui css file

cypress/integration/authentication.spec.js, cypress/integration/item/favorite/favoriteItem.spec.js, src/components/item/ItemContent.js, src/components/main/Home.js, src/components/main/Items.js, src/components/main/ItemsGrid.js, src/components/main/ItemsTable.js, src/components/main/TableToolbar.js
This allows each page to choose what to display in the table / Grid items.
close #136
=> feat: choose what to display in Items header

cypress.json, cypress/fixtures/apps.js, cypress/fixtures/apps/app.html, cypress/integration/item/apps/apps.spec.js, cypress/support/commands.js, cypress/support/server.js, package.json, yarn.lock
This PR adds tests for the apps workflow. I think it will be interesting for you @Julien-Torrent to get a glimpse at how we get apps to work. 
close #166
=> test: add test for apps

cypress/fixtures/recycleBin.js, cypress/integration/item/delete/gridRecycleItem.spec.js, cypress/integration/item/delete/listDeleteItem.spec.js, cypress/integration/item/delete/listDeleteItems.spec.js, cypress/integration/item/delete/listRecycleItem.spec.js, cypress/integration/item/delete/listRecycleItems.spec.js, cypress/support/commands.js, cypress/support/server.js, package.json, src/components/App.js, src/components/RecycleBinScreen.js, src/components/main/DeleteItemDialog.js, src/components/main/MainMenu.js, src/config/messages.js, src/config/paths.js, src/config/selectors.js, src/middlewares/notifier.js, yarn.lock
close #201 
Needs these PR to be closed before merging:
- https://github.com/graasp/graasp/pull/79
- https://github.com/graasp/graasp-recycle-bin/pull/6
- https://github.com/graasp/graasp-query-client/pull/67
=> feat: add recycle bin

cypress/fixtures/categories.js, cypress/integration/item/share/categories.spec.js, cypress/integration/item/share/shareItem.spec.js, cypress/integration/item/share/tags.spec.js, cypress/support/commands.js, cypress/support/server.js, src/components/item/sharing/CategorySelection.js, src/components/item/sharing/CustomizedTagsEdit.js, src/config/selectors.js, src/langs/fr.json
close #260 
- add preview for tags
=> feat: preview tags

cypress/integration/item/analytics/analytics.spec.js, cypress/integration/item/chatbox/chatbox.spec.js, cypress/support/constants.js, src/components/common/AnalyticsDashboardButton.js, src/components/common/HideButton.js, src/components/context/CopyItemModalContext.js, src/components/context/LayoutContext.js, src/components/context/MoveItemModalContext.js, src/components/item/ItemContent.js, src/components/item/header/ItemHeaderActions.js, src/components/item/sharing/CategorySelection.js, src/components/main/GraaspAnalyzer.js, src/components/main/ItemMenu.js, src/components/main/ItemScreen.js, src/components/main/TreeModal.js, src/config/constants.js, src/config/selectors.js, src/middlewares/notifier.js, yarn.lock
=> feat: add action dashboard

cypress/fixtures/apps/app.html, cypress/integration/item/apps/apps.spec.js, cypress/integration/item/copy/listCopyItem.spec.js, cypress/integration/item/share/itemLogin.spec.js, package.json, src/components/Root.js, src/components/common/HideButton.js, src/components/item/ItemContent.js, src/components/main/ItemScreen.js, src/utils/membership.js, yarn.lock
=> refactor: update app item data

src/components/item/ItemContent.js
=> refactor: set text editor height to fix scrolling

cypress/integration/item/chatbox/chatbox.spec.js, cypress/support/server.js, src/components/common/Chatbox.js
=> feat: update chatbox props

src/components/main/ItemsGrid.js, src/components/main/ItemsTable.js, src/components/main/ItemsToolbar.js, src/components/main/TableToolbar.js, yarn.lock
=> 244 change table toolbar behavior

package.json, src/components/common/Chatbox.js, yarn.lock
This PR adds the clear chat props to the chatbox.
closes #339
=> feat: add clear chat prop

.github/workflows/cdelivery-s3-caller.yml, .github/workflows/cdeployment-s3-caller.yml, .github/workflows/cintegration-s3-caller.yml
TO REMEMBER: change commit hash
close #410
=> ci: add sentry to workflows

cypress/fixtures/chatbox.js, cypress/integration/item/chatbox/chatbox.spec.js, cypress/support/commands.js, cypress/support/server.js, package.json, src/components/common/Chatbox.js, src/components/context/LayoutContext.js, src/components/layout/Header.js, src/enums/chatbox.js, src/enums/index.js, yarn.lock
This PR adds the UI for viewing and interacting with chat notifications.
For visuals refer to graasp/graasp-chatbox#46.
closes #405
=> feat: add mentions

cypress/fixtures/members.js, cypress/integration/memberProfile.spec.js, src/components/member/EmailPreferenceSwitch.js, src/components/member/MemberProfileScreen.js, src/config/constants.js, src/config/selectors.js, yarn.lock
This PR adds a select to choose email notification frequency.
The 2 options currently are `always` and `never` a third option would be a daily digest.
closes #429
=> feat: add profile email frequency switch

src/components/main/ImportH5P.js, src/langs/en.json, src/langs/fr.json, src/utils/uppy.js
=> refactor: fix file upload translations

cypress/integration/item/favorite/favoriteItem.spec.js, src/utils/member.js
=> fix: fix undefined favorite item list

.github/workflows/cdelivery-s3-caller.yml, .github/workflows/cdeployment-s3-caller.yml, .github/workflows/cintegration-s3-caller.yml, .github/workflows/cypress.yml, .github/workflows/update-staging-version.yml
=> refactor: update workflows version

src/components/common/CookiesBanner.tsx
=> refactor: set cookie domain

package.json, src/components/item/ItemContent.tsx, src/components/main/ItemActions.tsx, yarn.lock
=> fix: apply secondary color for toolbar, show creator in items

yarn.lock
=> chore: update graasp-translations

cypress/e2e/item/publish/coEditorSettings.cy.js, yarn.lock
Somehow #516 merged successfully with an eslint error, this fixes it. It later prevents the tag from being pushed.
=> Fix eslint issue in #516

src/components/item/ItemContent.tsx
=> fix: hide etherpad chat

package.json, src/components/main/ItemTypeTabs.tsx, src/components/main/NewItemModal.tsx, yarn.lock
=> fix: add scrollable tabs to new item modal

cypress/e2e/item/create/createFolder.cy.ts, src/components/main/ItemCard.tsx, src/components/main/NewItemModal.tsx
=> fix: clear new form on submit

src/components/main/MainMenu.tsx
=> feat: freeze sentry user feedback

src/components/item/ItemContent.tsx
This reverts commit c24b63318bc592dfd4cfec6ec15e2af387030f48.
=> Revert "fix: allow apps to resize (#922)"

src/components/item/sharing/ItemSharingTab.tsx
=> feat: filter memberships for same member to render highest permission only

src/components/main/ItemMenu.tsx
=> fix: add key prop to duplicate item main menu

package.json, src/components/item/form/DocumentForm.tsx, yarn.lock
=> fix: cant remove flavor

src/components/item/form/DocumentForm.tsx
=> fix: remove duplicate none doc flavor

src/components/Root.tsx, src/components/file/FileDashboardUploader.tsx, src/components/file/UppyContext.tsx, src/components/item/header/ModeButton.tsx, src/components/main/NewItemModal.tsx, yarn.lock
In this PR:
- dismiss status bar when files are uploaded
- automatically close new item dialog on file upload complete
- use stacked notifications for react-toastify
https://github.com/graasp/graasp-builder/assets/39373170/5a0a472f-e62b-4798-84d6-9e3e827dc01d
=> fix: update notifs and dismiss uppy status

package.json, src/components/App.tsx, src/components/item/MapView.tsx, src/components/main/Items.tsx, src/components/pages/MapItemsScreen.tsx, src/config/paths.ts, yarn.lock
This PR adds a new route `/map` that will display the map "in full screen". This is used by the mobile app to display the map.
=> feat: update map for mobile use

package.json, yarn.lock
Use updated UI dependency to use finalized font scale.
=> fix: update graasp ui to use improved font scale

src/components/item/settings/UpdateLicenseDialog.tsx
=> fix: allow license preview for license modal

package.json, src/components/item/MapView.tsx, yarn.lock
Update map, and pass full item parent to the map. Needed to get the permission over the parent.
=> feat: update map, pass parent item

package.json, src/components/item/ItemContent.tsx, yarn.lock
=> fix: allow apps to dynamically resize in builder

package.json, yarn.lock
add the following features: https://github.com/graasp/graasp-map/pull/126
=> feat: update map

cypress/e2e/item/share/shareItem.cy.ts, package.json, src/components/item/publish/publicationButtons/PublishedButton.tsx, src/components/item/sharing/shortLink/PlatformIcon.tsx, src/components/item/sharing/shortLink/PlatformSelect.tsx, src/components/item/sharing/shortLink/ShortLinkDialogContent.tsx, src/components/item/sharing/shortLink/ShortLinkDisplay.tsx, src/components/item/sharing/shortLink/ShortLinkMenu.tsx, src/components/item/sharing/shortLink/ShortLinksRenderer.tsx, src/config/selectors.ts, src/utils/shortLink.ts, yarn.lock
Fix shortlinks given changes in sdk
=> fix: shortlinks

cypress/e2e/item/create/createLink.cy.ts, cypress/fixtures/links.ts, src/components/item/form/link/LinkForm.tsx, yarn.lock
=> feat: validate name as a required value

cypress/e2e/memberships/createItemMembership.cy.ts, package.json, src/components/item/sharing/CreateItemMembershipForm.tsx, yarn.lock
Use new query client to share item.
=> feat: update query client for share item

package.json, src/components/item/header/ModeButton.tsx, yarn.lock
Based on #1432 
- **fix: update mode icons**
=> fix: update mode icon

src/langs/en.json
=> fix: fix hide setting name

src/components/item/edit/EditModal.tsx, src/components/item/form/FileForm.tsx, src/components/item/form/FolderForm.tsx
=> refactor: use react hook form in edit file form

cypress/support/server.ts, package.json, src/components/pages/RecycledItemsScreen.tsx, yarn.lock
=> feat: get recycled items

src/components/item/edit/EditModal.tsx, src/components/item/form/file/FileForm.tsx, src/components/item/form/file/UploadFileModalContent.tsx, src/components/item/form/link/LinkForm.tsx, src/components/main/NewItemModal.tsx
=> refactor: refactor file upload modal

src/components/item/edit/EditModal.tsx, src/components/item/shortcut/EditShortcutForm.tsx
=> refactor: refactor edit shortcut modal

src/components/main/ImportH5P.tsx, src/components/main/NewItemModal.tsx
=> refactor: refactor h5p form
