graasp/graasp-builder

src/components/context/EditItemModalContext.js

This PR fixes the edition of items.
The editor no longer shows the previous edited value.
closes #191

fix: discard changes when the modal is closed

---

src/components/item/sharing/CategorySelection.js
src/components/item/sharing/CustomizedTags.js
src/components/item/sharing/CustomizedTagsEdit.js
src/components/item/sharing/ItemSharingTab.js
src/config/constants.js
src/config/selectors.js
src/langs/en.json
src/utils/item.js
yarn.lock

- fix the canEdit attribute for category selection, when user don't have editting right, the menu will be disabled
- add a input form to set customized tags for the item (in pic above)
- age range => level
- Now options for disciplines are ordered alphabetically, while options for levels maintained the logical order

fix canEdit for category, add customized tag feature

---

src/components/main/ImportZip.js
src/langs/en.json
src/langs/fr.json
yarn.lock

This PR tries to add some indications on the import zip feature. Unfortunately, I think the websockets/refresh of the page get involved and prevent the onRequest notifications to be displayed. I've added a small sentence in the modal, it might help. 
close #271

refactor(import-zip): add translations, update on upload notifications

---

src/components/common/PlayerViewButton.js
src/components/common/ShareButton.js
src/components/item/header/ItemHeaderActions.js

This PR changes the header button size to `medium` to make them consistant with the other buttons.
closes #308

fix: change header button size to `medium` for consistency

---

cypress/integration/item/create/importZip.spec.js
cypress/integration/item/move/listMoveMultiple.spec.js
cypress/integration/item/share/tags.spec.js
cypress/support/constants.js
package.json
src/components/common/CropModal.js
src/components/context/EditItemModalContext.js
src/components/context/FlagItemModalContext.js
src/components/item/FolderDescription.js
src/components/item/ItemContent.js
src/components/item/form/DocumentForm.js
src/components/item/form/FolderForm.js
src/components/item/sharing/CCLicenseDialog.js
src/components/item/sharing/CreateItemMembershipForm.js
src/components/item/sharing/CustomizedTagsEdit.js
src/components/item/sharing/ItemPublishConfiguration.js
src/components/main/DeleteItemDialog.js
src/components/main/NewItemButton.js
src/components/main/NewItemModal.js
src/components/main/TreeModal.js
src/config/constants.js
yarn.lock

This PR updates some properties in TextEditor / DocumentItem corresponding to the changes in graasp-ui.
It also removes all buttons to use the Button in @graasp/ui.
close #304

refactor: use graasp button

---

cypress/integration/memberships/createItemMembership.spec.js
src/components/item/sharing/CreateItemMembershipForm.js

This PR fixes the issue where the email textfield would keep the email value after inviting a member.
closes #334

fix: empty email field after invite completes

---

cypress/fixtures/apps.js
cypress/fixtures/apps/apps.js
cypress/integration/item/edit/editFolder.spec.js
cypress/integration/item/publish/publishedItem.spec.js
cypress/support/commands/item.js
src/components/common/HideButton.js
src/components/common/PublishButton.js
src/components/context/EditItemModalContext.js
src/components/item/form/AppForm.js
src/components/item/form/BaseItemForm.js
src/components/main/NewItemModal.js
src/config/constants.js

This PR fixes:
- Editing name of item field
- Editing App name field after selecting app in dropdown
- Publish icon size
- Missing span for Tooltip on hidden IconButton for HideButton
Tests now do a `{selectall}{backspace}some text` in the type instead of `{selectall}some text` so that the empty field can be tested too.
closes #332 
closes #330

Fix item name Field and App name Field

---

cypress/fixtures/categories.js
cypress/integration/item/publish/coEditorSettings.spec.js
cypress/integration/item/publish/publishedItem.spec.js
cypress/support/commands.js
cypress/support/server.js
package.json
src/components/item/publish/CoEditorSettings.js
src/components/item/publish/ItemPublishButton.js
src/components/item/publish/ItemPublishConfiguration.js
src/config/constants.js
src/config/selectors.js
src/langs/en.json
yarn.lock

Add co-editor display setting in publish tab

feat: add co-editor settings

---

cypress/fixtures/links.js
cypress/integration/item/settings/itemSettings.spec.js
cypress/integration/item/view/utils.js
cypress/integration/item/view/viewLink.spec.js
package.json
src/components/item/ItemContent.tsx
src/components/item/publish/CategorySelection.tsx
src/components/item/settings/LinkSettings.tsx
src/config/constants.js
yarn.lock

This PR corrects a type typo and set the default link settings to: button=true, iframe=false (I inverted)
close #472

feat: link iframe are disabled by default

---

src/components/item/form/AppForm.tsx
src/components/item/settings/ItemSettings.tsx

This PR fixes dumb issues created in #514:
- comparison of the strings should be made in lowercase
- resizable setting should be show when `ItemType` is `app`
closes #528

fix: case-insensitive autocomplete comparison

---

package.json
src/components/main/MainMenu.tsx
src/config/constants.ts
yarn.lock

close #545
After some feedback I've been suggested to add the tutorials' link at some place in builder. I think the footer is a good place so it's not too highlighted, but I'm happy to get your feedback.

feat: add tutorial footer menu item

---

README.md
package.json

doc: update readme and package json to include author and contributors

---

package.json
src/components/main/ItemsTable.tsx
yarn.lock

feat: improve accessibility for mainmenu and table

---

cypress/e2e/header.cy.js
package.json
src/components/main/Main.tsx
src/config/selectors.ts
yarn.lock

[Peek 2023-02-03 18-11.webm](https://user-images.githubusercontent.com/14943421/216664944-4e5c49ab-5d2b-4ff4-9ebd-05e0a3356e78.webm)

feat: add platform switch to builder

---

.eslintrc
package.json
src/components/common/AnalyticsDashboardButton.tsx
src/components/common/CollapseButton.tsx
src/components/common/EditItemCaptionButton.tsx
src/components/common/ItemMetadataButton.tsx
src/components/common/PlayerViewButton.tsx
src/components/common/PublishButton.tsx
src/components/common/RecycleButton.tsx
src/components/context/CurrentUserContext.tsx
src/components/context/LayoutContext.tsx
src/components/file/FileUploader.js
src/components/item/ItemMain.tsx
src/components/item/header/ItemHeader.tsx
src/components/item/header/ItemHeaderActions.tsx
src/components/item/publish/ItemPublishTab.tsx
src/components/item/settings/ItemSettings.tsx
src/components/item/settings/ItemSettingsButton.tsx
src/components/item/sharing/CreateItemMembershipForm.tsx
src/components/item/sharing/SharingLink.tsx
src/components/item/sharing/TableRowDeleteButtonRenderer.tsx
src/components/main/Item.tsx
src/components/main/ItemMenu.tsx
src/components/main/MainMenu.tsx
src/config/constants.ts
src/utils/membership.ts
yarn.lock

In this PR I propose to change the `Share` icon to better represent that this menu is related to sharing with people.
Previously:
Proposed change:
And the link box was styled with the `text-overflow: ellipsis` to better show the link could not be displayed fully:
IconButtons were also all wrapped in `span`s to ensure they stay round.
TODO:
Change `Favorite Items` icon from a heart to a star to be in ligne with the `Add to Favorites` icon in item actions.
closes #550

Change `Share` icon and improve layout of item header actions

---

src/components/item/FolderDescription.tsx

This PR ensures that the content saved by the text editor is an empty string when the editor is cleared.
closes #570

fix(quill): save empty string when content is empty

---

cypress/support/viewUtils.js
src/components/item/header/ItemHeaderActions.tsx

This PR removes the player button from the item header actions.
closes #574

fix: remove player button from item header actions

---

src/components/App.tsx

This PR uses the `CustomInitialLoader` from @graasp/ui for the first screen when the builder is fetching the member. 
It would be super cool be able to statically generate that in the `idnex.html` so there is no "white screen of death" when the bundle takes a bit longer to load.
Maybe this could be accomplished when using vite ?
closes #587

fix: use `CustomInitialLoader` on first load

---

src/components/common/HideButton.tsx
src/components/table/BadgesCellRenderer.tsx
src/config/notifier.ts
yarn.lock

This PR fixes an issue where item statuses stopped showing.
~~There is still a reactivity issue, because the queries are not invalidating correctly, so the statuses do not updates when a single mutation updates them. This needs to be investigated further.~~
Invalidation should now work as expected. One trade-off is that **all** itemTags queries that target multiple items will refetch when one itemTag is changed. It looks like invalidation of query keys is made in order of the elements in the array, so it is not easily possible to invalidate one of the use many queries if it does not target the first id in the list:
Example of itemTags query keys: `["items", "itemTags", "many", "idA", idB", idC", ...]` in this case it is possible to invalidate this query by using one of these:
- …

fix: item status

---

src/components/item/form/BaseItemForm.tsx
src/components/item/form/DocumentForm.tsx
src/components/item/form/EtherpadForm.tsx
src/components/item/form/FolderForm.tsx

Closes #619
Adds a * to the name text input field for `Folder`, `Document` and `Etherpad`.
Might want use `BaseItemForm` in `EtherpadForm`?

feat: adds required symbol for name of folder, document and etherpad

---

cypress/e2e/item/delete/gridRecycleItem.cy.ts
cypress/e2e/item/delete/listRecycleItem.cy.ts
cypress/support/commands.ts
cypress/support/server.ts
package.json
yarn.lock

Fix some recycle tests, update query client dependency.
This will mainly fix optimistic mutations for "many items" calls that are async.

Test query client

---

cypress/fixtures/files.ts
package.json
src/components/context/EditItemModalContext.tsx
src/config/selectors.ts
yarn.lock

closes #624
Requires change to the backend:
- currently schema does not allow to modify the extra of a file or s3File graasp/graasp#422

feat: allow to set an `altText` on images

---

src/components/member/PasswordSetting.tsx

This PR fixes a minor bug where the password error text would be displayed inside the new password field instead of as a helper-text. This was a small typo.

fix: password error shown in helpertext

---

cypress/e2e/item/publish/coEditorSettings.cy.ts
cypress/e2e/item/publish/publishedItem.cy.ts
cypress/e2e/item/publish/tags.cy.ts
cypress/support/server.ts
src/components/item/header/ItemHeaderActions.tsx

fix: hide publish tab for reader and public

---

src/components/item/header/ItemHeaderActions.tsx

This PR adds the item menu button in the header. 
It's not pretty at all, but at least functional, so we don't forget it when redesigning the layout.
close #687

feat: add item menu in item header

---

cypress/e2e/item/create/createDocument.cy.ts
cypress/e2e/item/create/createFolder.cy.ts
cypress/fixtures/documents.ts
cypress/fixtures/items.ts
src/utils/item.ts

this fix was made to disable create new item button for whitespaces titles
relates #781

fix: prevent adding new item blank spaces

---

index.html
src/components/item/ItemMain.tsx
src/components/main/ItemsToolbar.tsx

style: wrapping long item name

---

src/components/main/AppCard.tsx

This should fix the issue of the description staying in "loading" mode when it is an empty string.
With `??` it will only show the skeleton when the data is not yet available. 
Example below, the apps have loaded but the description of Task Management and Text Input are simply `""` so they show the Skeleton even if they are loaded:

fix: use `??` instead of `||` for skeleton in `AppCard.tsx`

---

src/components/item/sharing/shortLink/ShortLinkSkeleton.tsx

The skeletons of the short links when loading weren't responsive on small screen when the drawer menu is open.

feat: improve the responsivity of the skeletons

---

src/utils/item.ts

This PR proposes to simplify the validation of urls to allow some urls that currently fail. See #756 
[Test urls](https://regex101.com/r/iOZk6g/2)
@dialexo Do you think we would expose to possible security threats by allowing all non-whitespace characters in urls ?

fix(link): allow all non-whitespace chars in urls

---

cypress/e2e/item/edit/editApp.cy.ts
cypress/e2e/item/publish/coEditorSettings.cy.ts
cypress/e2e/item/settings/itemSettings.cy.ts
cypress/support/editUtils.ts
package.json
src/components/Root.tsx
src/components/common/EditButton.tsx
src/components/item/ItemMain.tsx
src/components/main/Main.tsx
src/langs/constants.ts
src/langs/en.json
src/langs/fr.json
yarn.lock

In this PR:
- update the main component 
- cleanup some of the logic and components below the main component

fix: update main component and cleanup

---

package.json
src/components/main/itemSelectionModal/AccessibleNavigationTree.tsx
src/components/main/itemSelectionModal/ChildrenNavigationTree.tsx
src/components/main/itemSelectionModal/RootNavigationTree.tsx
yarn.lock

- Use the filter by types in the `useAccessibleItems` hooks in `RootNavigationTree` and `AccessibleNavigation`.
- Use filter array methods on data of `useChildren` hook in `ChildrenNavigationTree`.

feat: hide none-folder in the move modal

---

src/components/common/CropModal.tsx

Start the crop at 100% of the input image.

fix: use 100% for crop

---

src/components/main/ItemCard.tsx
src/components/table/ItemNameCellRenderer.tsx

This PR updates the size used for thumbnails in the Grid and their styling:
Before:
After:

fix: make thumbnails nice in grid view

---

src/components/main/ItemsToolbar.tsx

fix(chore): set FormControlLabel max width to limit show only me switch

---

src/components/main/Main.tsx

fix: invert colors for mobile platform switch

---

cypress/e2e/item/view/viewFolder.cy.ts
package.json
src/components/item/ItemContent.tsx
src/components/item/ItemSearch.tsx
yarn.lock

I added back the search in the folder view.

fix: add item search in folder view

---

src/components/item/ItemMain.tsx
src/langs/en.json
src/langs/fr.json

fix: rename chatbox title

---

index.html
package.json
yarn.lock

feat: use new font

---

src/components/item/header/ItemHeaderActions.tsx

in this PR fix an issue related to display interpolation data on mouse hover for chatbox name
#1141

fix: display interpolation data on mouse hover for chatbox name

---

package.json
src/components/item/MapView.tsx
src/components/main/Items.tsx
src/components/pages/MapItemsScreen.tsx
yarn.lock

Pass mobileApp param to the map to handle open in player.

feat: send mobile-app param to map

---

package.json
src/components/item/MapView.tsx
src/components/item/header/ItemHeaderActions.tsx
src/components/item/settings/GeolocationPicker.tsx
src/components/main/Items.tsx
src/components/pages/MapItemsScreen.tsx
yarn.lock

- handle correctly inherited geoloc in geoloc form.
- add viewItemInBuilder

feat: update map

---

package.json
src/components/item/form/link/LinkForm.tsx
yarn.lock

In this PR I fix an issue where the embedding option would not be shown because the html prop in not returned when no reiche media embedding is possible.
I also fixed the iframe sizing issue (by using the ui PR)

fix: embedding setting and iframe display

---

cypress/support/viewUtils.ts
src/components/item/ItemContent.tsx
src/components/main/NewItemModal.tsx

The default link type is a bare link, but when not specified the backend creates a link with the showLinkButton to true. The default setting was added in the frontend to give the expected result.

fix: link default to use showLinkButton = false

---

cypress/e2e/item/hide/hideItem.cy.ts
cypress/support/server.ts
cypress/support/utils.ts
package.json
src/utils/item.test.ts
src/utils/item.ts
yarn.lock

In this PR:
- add unit tests with vitest
- remove unused utils functions and use functions from sdk
- fix a bug with the mock server for getting children

chore: cleanup old code and use sdk functions

---

package.json
yarn.lock

In this PR I update builder with the new version of UI that contains the fix to not set a maxHeight of 70vh on the app iframe.
I deployed this to dev to test and it works as expected.

fix: update app max height setting

---

src/components/item/ItemContent.tsx
src/components/item/ItemSearch.tsx

Before this PR, the search in children does not allow to write capital letters, and the check is case sensitive, so it's impossible to find "Public" for example. 
So I lowercase both strings on check, and allow to write capital letters (that does not change anything, but at least it reflects the user input)

fix: allow capital letter in search, case insensitive search

---

src/components/item/FolderContent.tsx
src/components/item/copy/CopyModal.tsx
src/components/item/move/MoveModal.tsx
src/components/main/list/SelectionContext.tsx
src/components/main/list/useDragSelection.tsx
src/components/pages/RecycledItemsScreen.tsx
src/components/pages/home/HomeScreen.tsx
src/config/constants.ts

Selecting items trigger lots of renders.
- Moved down DragSelection (so some duplication happens). Some manual adjustement is necessary because of margin and padding.
-  do not fetch items for modal if they are not opened.

fix: prevent modal calls on selection

---

src/components/main/list/useDragSelection.tsx

Currently there's a small bug happening if you drag and you specifically click on an icon (svg), it will allow you to drag but then it will trigger the multi selection. 
This should fix the problem.

fix: does not trigger drag on mousedown svg

---

src/components/Root.tsx
src/components/main/Main.tsx
src/components/main/MainMenu.tsx

In this PR I updated the icons of the main menu to use lucide alternatives, below is a before and after:
ref #1431

fix: udpate menu icons to lucide

---

.github/workflows/deploy-dev.yml
cypress/e2e/authentication.cy.ts
cypress/e2e/header.cy.ts
cypress/e2e/item/chatbox/chatbox.cy.ts
cypress/e2e/memberships/deleteItemMembership.cy.ts
cypress/support/constants.ts
index.html
package.json
src/components/App.tsx
src/components/common/SelectTypes.tsx
src/components/common/UserSwitchWrapper.tsx
src/components/item/ItemSearch.tsx
src/components/main/Main.tsx
src/components/main/MainMenu.tsx
src/components/main/NewItemButton.tsx
src/components/table/ShowOnlyMeButton.tsx
src/config/selectors.ts
yarn.lock

In this PR: 
Still todo is #1502 
closes #1495

feat: add umami tags to track actions

---

src/components/common/CropModal.tsx

In this PR I refactor the crop modal execution to fix an issue where the thumbnail would be artificially inflated, resulting in very large uploads. 
This code was taken from account where this fix was initially made.

fix: update crop modal to not inflate image sizes

---

src/components/item/edit/EditModal.tsx
src/components/item/form/AppForm.tsx
src/components/item/form/BaseItemForm.tsx
src/components/item/form/DescriptionForm.tsx
src/components/item/form/FileForm.tsx
src/components/item/form/FolderForm.tsx
src/components/item/form/NameForm.tsx
src/components/item/form/link/LinkForm.tsx
src/components/main/NewItemModal.tsx

- Refactor FolderForm to use react-hook-form. 
- Simplify `DescriptionForm` and remove `updatedProperties`, `item` props for more straightforward values `description` and `descriptionPlacement`.
- Use this form for edit as well.
ref #1522

refactor: refactor folder form

---

src/components/item/edit/EditModal.tsx
src/components/item/form/BaseItemForm.tsx
src/components/item/form/FolderForm.tsx

refactor: use react hook form for base item form

---

src/components/item/FolderContent.tsx

fix: clear selection on navigation

---

src/components/item/edit/EditModal.tsx
src/components/item/form/FileForm.tsx
src/components/item/form/NameForm.tsx
src/components/item/shortcut/EditShortcutForm.tsx
src/utils/item.ts

- Create ShortcutEditForm and apply react-hook-form
- Modify LinkForm (edit) so it fully uses react-hook-form. It sends itself the `editItem` request, so we avoid drilling up props.
- also fix the bug of editing files by sending only `altText` for editing `extra` 
Once all forms are refactored, next move would be to use specific endpoints for each item type. 
ref #1551 
close #1522

feat: submit individually file data for edit

---

cypress/e2e/item/settings/itemSettings.cy.ts
src/components/item/edit/EditModal.tsx
src/components/item/form/BaseItemForm.tsx
src/components/item/form/description/DescriptionAndPlacementForm.tsx
src/components/item/form/description/DescriptionPlacementForm.tsx
src/components/item/form/file/FileForm.tsx
src/components/item/settings/ItemSettingsProperties.tsx

I updated the base item form (edit modal for link, app, etherpad and h5p).
I removed the description placement in the settings page, it was not matching well with my refactor, and it didn't make much sense to have it in the settings. We can discuss it. 
ref #1551

refactor: refactor edit base item form

---

cypress.config.ts
src/components/item/form/link/LinkForm.tsx

fix: link crash when url is not valid
